db:
  host: localhost
  username: fylerx
  password: fylerx
  database: fylerx
  port: 5432
  sslmode: disable
  timezone: "Europe/Moscow"
http:
  port: 8080
crypto:
  passphrase: "passphrasewhichneedstobe32bytes!"
