name: codecov

on:
  push:
    branches: [main]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    environment: fylerx-test-env
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Get dependencies
        run: go get -t -v ./cmd/dispatcher/

      - name: Generate coverage report
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          verbose: true
